"""Validation table of the integrate-fork builds (reads out/<dir>/checks.json + build-receipt.json; no CAD).
Writes out/fr1-validation.md and out/fr1-validation.json."""
import hashlib, json, os
HERE = os.path.dirname(os.path.abspath(__file__))
REF = os.path.join(HERE, '..', 'out', 'stl')
BUILDS = [('_none-premerge', 'none', '--fast, sweeps 2 mm'), ('_none', 'none', '--fast, sweeps 2 mm'), ('_int-panel', 'panel', '--fast, sweeps 2 mm'),
          ('_int-keeper', 'keeper', '--fast, sweeps 2 mm'), ('_int-hood-yslide', 'hood=yslide', '--fast, sweeps 2 mm'),
          ('_int-hood-screw1', 'hood=screw1', '--fast, sweeps 2 mm'),
          ('_int-hood-yslide-r3m', 'hood=yslide', '--fast, sweeps 2 mm'), ('_int-hood-screw1-r3m', 'hood=screw1', '--fast, sweeps 2 mm'),
          ('_int-panel-r3m', 'panel', '--fast, sweeps 2 mm'), ('_int-keeper-r3m', 'keeper', '--fast, sweeps 2 mm'),   # fix-candidate VC-L3
          ('_int-pks1', 'panel,keeper,hood=screw1', '--fast, sweeps 2 mm'),                                          # fix-candidate VC-L2
          ('.', 'all (panel A2, keeper, hood yslide)', 'full: renders, STEP, sweeps 1 mm')]
CUR = {n: hashlib.sha256(open(os.path.join(HERE, n), 'rb').read()).hexdigest() for n in ('checks.py', 'build_d2.py')}
CUR_LAYOUT = hashlib.sha256(open(os.path.join(HERE, 'layout.py'), 'rb').read()).hexdigest()
res, md = [], ['| build dir | D2_FR | mode | built_at | checks version | categories pass | critical features (pass / info / fail) | joints | sweeps | removals | driver | service driver | release_access | unresolved info rows (unclassified thin spots) | layout.py | STLs changed vs r2 |',
               '|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|']
for d, sel, mode in BUILDS:
    p = os.path.join(HERE, 'out', d)
    c = json.load(open(os.path.join(p, 'checks.json')))
    rc = json.load(open(os.path.join(p, 'build-receipt.json')))
    S = {s['check']: s for s in c['summary']}
    ok = sum(1 for s in c['summary'] if s['status'] == 'pass')
    cf = S['critical_features']
    joints = [r for r in c['results']['critical_features'] if r.get('kind') == 'joint' or str(r.get('id', '')) in
              {j for j in ()}]
    jr = [r for r in c['results']['critical_features'] if 'gated_exceptions' in r]
    ch = []
    for f in sorted(os.listdir(os.path.join(p, 'stl'))):
        if f.endswith('.stl'):
            h = hashlib.sha256(open(os.path.join(p, 'stl', f), 'rb').read()).hexdigest()
            if h != hashlib.sha256(open(os.path.join(REF, f), 'rb').read()).hexdigest():
                ch.append('%s %s' % (f[:-4], h[:8]))
    f = lambda k: '%d/%d' % (S[k]['passed'], S[k]['n']) if S.get(k) else '-'
    ra = 'n/a (0 rows: nothing to release)' if S['release_access']['n'] == 0 else f('release_access')
    if any(r.get('id') == 'no_release_required' for r in c['results']['release_access']):
        ra += ' (no_release_required row)'
    if S['release_access'].get('error'):
        ra += ' FAIL: ' + S['release_access']['error']
    src = rc.get('sources', {})
    # fix-candidate VC-M1: informational rows that need an owner decision stay visible (never summarised away)
    un = c['results'].get('unclassified_thin_spots') or []
    unr = '; '.join('%s t %.2f at %s (near %s)' % (u['part'], u['t_min'], tuple(u['at']), u.get('nearest_entry')) for u in un) or 'none'
    lv = 'current' if src.get('layout.py') == CUR_LAYOUT else 'older'
    cv = ('current (re-merged r3 + no-release row)' if all(src.get(n) == CUR[n] for n in CUR) else
          'PRE-MERGE r3 checks (before 13:52)' if (rc.get('built_at') or '') < '2026-10-05 13:52' else
          'older fork checks (re-merged, before the no-release row)')
    row = dict(dir='out/' + d if d != '.' else 'out/', d2_fr=sel, checks_version=cv, variant=c.get('variant'), built_at=rc.get('built_at'),
               categories='%d/%d' % (ok, len(c['summary'])), critical=(cf['passed'], cf['info'], cf['failed']),
               joints='%d/%d pass' % (sum(r['status'] == 'pass' for r in jr), len(jr)), release_access=ra,
               changed=ch or ['none: all 11 identical to r2'], release_candidate=rc.get('cad_release_candidate'),
               unresolved_info=un, layout_version=lv)
    res.append(row)
    md.append('| %s | %s | %s | %s | %s | %s | %d / %d / %d | %s | %s | %s | %s | %s | %s | %s | %s | %s |' % (
        row['dir'], sel, mode, row['built_at'], cv, row['categories'], cf['passed'], cf['info'], cf['failed'], row['joints'],
        f('sweeps'), f('removals'), f('driver'), f('service_driver'), ra, unr, lv, ', '.join(row['changed'])))
json.dump(res, open(os.path.join(HERE, 'out', 'fr1-validation.json'), 'w'), indent=1)
open(os.path.join(HERE, 'out', 'fr1-validation.md'), 'w').write(
    '# FR1 validation (generated by fr1_validation.py from the build checks.json; computed checks only)\n\n' + '\n'.join(md) + '\n')
print('\n'.join(md))
